<?php
/** @var \envtesting\Suit $suit */
/** @var \envtesting\Filter $filter */
?><!DOCTYPE html>
<html lang="en-us" dir="ltr">
<head>
	<meta charset="UTF-8">
	<title><?= $title ?></title>
	<meta name="robots" content="noindex, nofollow, noarchive, noodp"/>

	<link rel="stylesheet" type="text/css" media="all"
	      href="//current.bootstrapcdn.com/bootstrap-v204/css/bootstrap-combined.min.css"/>
	<style type="text/css">
		tr.warning {
			background: #F89406;
		}

		tr.disabled {
			text-decoration: line-through;
		}

		tr.error, tr.exception {
			background: #BD362F;
		}

		tr.ok {
			background: #5BB75B;
		}

		.modal pre {
			overflow: auto;
			height: 150px;
		}

		body {
			padding-top: 20px;
		}

		.icon-info-sign {
			float: right;
		}

		table a {
			color: #333;
		}

	</style>
</head>
<body>
<div class="container">
	<div class="row">
		<div class="span12">
			<? if ($filter->isActive()) { ?>
			<div class="alert">
				<a href="?" class="close">&times;</a>Results are filtered!
			</div>
			<? } ?>


			<table class="table table-condensed">
				<thead>
				<tr>
					<th></th>
					<th title="Warning | Error | Ok or disabled">Result</th>
					<th title="Unique test name">
						Name<?= $filter->name ? ' = <span class="label label-inverse">' . $filter->name . '</span>' : ''?>
					</th>
					<th title="Test group">
						Group<?= $filter->group ? ' = <span class="label label-inverse">' . $filter->group . '</span>' : ''?>
					</th>
					<th title="Test type">
						Type<?= $filter->type ? ' = <span class="label label-inverse">' . $filter->type . '</span>' : ''?>
					</th>
					<th title="Notice eg. stable server">Notice</th>
					<th title="Test parameters">Options</th>
					<th title="Response message">Message</th>
				</tr>
				</thead>

				<tbody>

				<? foreach ($suit as $group => $tests) { ?>
					<? foreach ($tests as $order => $test/** @var \envtesting\Test $test */) { ?>
						<? $total++; ?>
					<tr class="<?= strtolower($test->getStatus())?>">
						<td>
							<i class="icon-<?= $test->isOk() ? 'ok' : 'remove' ?>"></i>
						</td>
						<td><?= $test->getStatus(); ?></td>
						<td><a href="?name=<?= $test->getName(); ?>"><?= $test->getName(); ?></a></td>
						<td><a href="?group=<?= $group ?>"><?= $group ?></a></td>
						<td>
							<a href="?type=<?= $test->getType(); ?>"><?= $test->getType(); ?></a>
						</td>
						<td><?= $test->getNotice(); ?></td>
						<td>
							<? if ($test->hasOptions()) { ?>
							<code><?= json_encode((array)$test->getOptions()); ?></code>
							<? } ?>
						</td>
						<td><?= $test->getStatusMessage(); ?></td>
					</tr>
						<? if ($test->isOk() && $test->isEnabled()) $ok++; ?>
						<? if (!$test->isEnabled()) $disabled++; ?>
						<? if ($test->isError()) $error++; ?>
						<? if ($test->isWarning()) $warning++; ?>
						<? } ?>

					<? } ?>
				</tbody>
			</table>

			<? if ($filter->isActive()) { ?>
			<p><a href="?" class="btn btn-primary">Cancel filter</a></p>
			<? } ?>

			<hr>
			<p>
				<? if ($disabled > 0) { ?><span class="badge badge-info"><?= $disabled ?> Disabled</span> <? } ?>
				<? if ($error > 0) { ?><span class="badge badge-important"><?= $error ?> Errors</span><? } ?>
				<? if ($warning > 0) { ?><span class="badge badge-warning"><?= $warning ?> Warnings</span><? } ?>
				<span class="badge badge-success"><?= $ok ?> OK</span>
				<span class="badge badge-inverse"><?= $total ?> total</span>
				<a data-toggle="modal" href="#about" class="icon-info-sign"></a>
			</p>
		</div>
	</div>


	<div class="row">

		<div class="span12">
			<div class="footer">

			</div>
		</div>

		<div class="modal hide" id="about">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Envtesting</h3>
			</div>
			<div class="modal-body">
				<p>Envtesting is fast simple and <strong>easy to use</strong> environment testing written in PHP.
					Can check library, services and services response. Produce console, HTML or CSV output.
				</p>

				<h4>Authors</h4>

				<p>
					<a href="http://www.wikidi.com">wikidi.com</a> and
					<a href="https://twitter.com/#!/OzzyCzech" title="Roman Ožana" target="_blank">@OzzyCzech</a>
				</p>


				<h4>Copyright & License</h4>

				<pre><? include __DIR__ . "/../../LICENSE.TXT"?></pre>

			</div>

			<div class="modal-footer">
				<a href="https://github.com/wikidi/envtesting" class="btn btn-primary" target="blank">Fork me on GitHub</a>
				<a href="#" class="btn btn-success" data-dismiss="modal">Thanks!</a>
			</div>


		</div>

	</div>
</div>


<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="//current.bootstrapcdn.com/bootstrap-v204/js/bootstrap.min.js"></script>


</body>
<!--
	Generated at <?= date('j.n.Y H:i:s') ?> by Envtesting
	https://github.com/wikidi/envtesting
-->
</html>