<?php
namespace envtesting\output;
/**
 * @var \envtesting\Suite $suite
 * @var \envtesting\Filter $filter
 */
?><!DOCTYPE html>
<html lang="en-us" dir="ltr">
<head>
	<meta charset="UTF-8">
	<title><?= $suite->getName() ?></title>
	<meta name="robots" content="noindex, nofollow, noarchive, noodp"/>

	<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">

	<style type="text/css">
		.table>tbody>tr.disabled>td,
		.table>tbody>tr.disabled>td>a {
			background-color: #cfcfcf;
			border-color: rgba(255, 255, 255, .3);
			color: #555;
		}

		.table>thead>tr>th {
			border: 0;
		}

		.table>tbody>tr.warning>td,
		.table>tbody>tr.warning>td>a {
			background-color: #F89406;
			border-color: rgba(255, 255, 255, .3);
			color: #593503;
		}

		.table>tbody>tr.danger>td,
		.table>tbody>tr.danger>td>a,
		.table>tbody>tr.exception>td,
		.table>tbody>tr.exception>td>a {
			background-color: #BD362F;
			border-color: rgba(255, 255, 255, .3);
			color: #661c1a;
		}

		.table>tbody>tr.success>td,
		.table>tbody>tr.success>td>a {
			background: #5BB75B;
			border-color: rgba(255, 255, 255, .3);
			color: #204020;
		}

		.modal pre {
			overflow: auto;
			height: 150px;
		}

		.glyphicon-question-sign {
			float: right;
			font-size: 18px;
			color: #555;
		}

		table a, table a:hover {
			color: #333;
		}

		footer {
			padding-top: 1em;
		}

		footer .label {
			margin-right: 5px;
		}

	</style>
</head>
<body>
<div class="container">
	<header class="row">
		<h3>Envtesting<?= $suite->getName() ? ' : ' . $suite->getName() : null; ?></h3>

		<? if ($filter->isActive()) { ?>
			<div class="alert alert-info">
				<a href="<?= Html::link() ?>" class="close">&times;</a>Test results are filtered!
			</div>
		<? } ?>
	</header>

	<div class="row">
		<table class="table table-condensed ">
			<colgroup style="width:25px;"/>
			<colgroup style="width:80px;"/>
			<colgroup style="width:150px;"/>
			<colgroup style="width:150px;"/>
			<colgroup style="width:120px;"/>
			<colgroup style="width:100px;"/>
			<thead>
			<tr>
				<th></th>
				<th title="Warning | Error | Ok or disabled">Result</th>
				<th title="Unique test name">
					Name<?= $filter->name ? ' = <span class="label label-default">' . $filter->name . '</span>' : '' ?>
				</th>
				<th title="Test group">
					Group<?= $filter->group ? ' = <span class="label label-default">' . $filter->group . '</span>' : '' ?>
				</th>
				<th title="Test type">
					Type<?= $filter->type ? ' = <span class="label label-default">' . $filter->type . '</span>' : '' ?>
				</th>
				<th title="Notice eg. stable server">Notice</th>
				<th title="Response message">Message</th>
			</tr>
			</thead>

			<tbody>
			<? $total = $ok = $disabled = $error = $warning = 0; ?>
			<? foreach ($suite as $group => $tests) { ?>
				<? foreach ($tests as $order => $test/** @var \envtesting\Test $test */) { ?>
					<? $total++; ?>
					<tr class="<?= Html::getStatusAsClass($test->getStatus()) ?>">
						<td>
							<i class="icon-<?= $test->isOk() ? 'ok' : 'remove' ?>"></i>
						</td>
						<td><?= $test->getStatus(); ?></td>
						<td><a href="<?= Html::link('name=' . $test->getName()) ?>"><?= $test->getName(); ?></a></td>
						<td><a href="<?= Html::link('group=' . $group); ?>"><?= $group ?></a></td>
						<td>
							<a href="<?= Html::link('type=' . $test->getType()) ?>"><?= $test->getType(); ?></a>
						</td>
						<td><?= $test->getNotice(); ?></td>
						<td>
							<?= nl2br($test->getStatusMessage()); ?>
							<? if ($test->hasOptions()) { ?>
								<br><code>Options: <?= json_encode((array)$test->getOptions()); ?></code>
							<? } ?>
						</td>

					</tr>
					<? if ($test->isOk() && $test->isEnabled()) $ok++; ?>
					<? if (!$test->isEnabled()) $disabled++; ?>
					<? if ($test->isError()) $error++; ?>
					<? if ($test->isWarning()) $warning++; ?>
				<? } ?>

			<?
			}
			$enabled = $total - $disabled; ?>
			</tbody>
		</table>


		<div class="btn-group">
			<a href="<?= Html::link(null, true) ?>" class="btn btn-primary" title="Refresh current tests"><i
					class="icon-refresh icon-white"></i> Refresh</a>
			<a href="<?= Html::link('output=csv', true) ?>" class="btn btn-default" title="Download CSV output">CSV <i
					class="icon-arrow-down"></i></a>
			<? if ($filter->isActive()) { ?>
				<a href="<?= Html::link(null) ?>" class="btn btn-danger" title="Cancel filter">Cancel filter</a>
			<? } ?>
		</div>
	</div>

	<footer class="row">
		<? if ($disabled > 0) { ?>
			<span class="label label-default">
					<?= $disabled ?> DISABLED <?= $total ? round(100 * $disabled / $total) : 0 ?>%
				</span>
		<? } ?>
		<? if ($error > 0) { ?>
			<span class="label label-danger">
					<?= $error ?> ERROR <?= $enabled ? round(100 * $error / $enabled) : 0 ?>%
				</span>
		<? } ?>
		<? if ($warning > 0) { ?>
			<span class="label label-warning">
					<?= $warning ?> WARNING <?= $enabled ? round(100 * $warning / $enabled) : 0 ?>%
				</span>
		<? } ?>
		<span class="label label-success">
					<?= $ok ?> OK <?= ($total - $disabled) ? round(100 * $ok / ($total - $disabled)) : 0 ?>%
				</span>
		<span class="label label-default"><?= $total ?> TESTS</span>
		<a data-toggle="modal" href="#about" class="glyphicon glyphicon-question-sign"></a>
	</footer>


	<div class="modal" id="about" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">×</button>
					<h3>Envtesting</h3>
				</div>
				<div class="modal-body">
					<p>Envtesting is fast simple and <strong>easy to use</strong> environment testing written in PHP.
						Can check library, services and services response. Produce console, HTML or CSV output.
					</p>

					<h4>Authors</h4>

					<p>
						<a href="http://www.wikidi.com">wikidi.com</a> +
						<a href="https://twitter.com/#!/OzzyCzech" title="Roman Ožana" target="_blank">@OzzyCzech</a>
					</p>

					<h4>Copyright & License</h4>

					<pre><? include __DIR__ . "/../../LICENSE.TXT" ?></pre>

				</div>

				<div class="modal-footer">
					<a href="https://github.com/wikidi/envtesting" class="btn btn-primary" target="blank">Fork me on GitHub</a>
					<a href="#" class="btn btn-success" data-dismiss="modal">Thanks!</a>
				</div>
			</div>
		</div>
	</div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
</body>
<!--
	Generated at <?= date('j.n.Y H:i:s') ?> by Envtesting
	https://github.com/wikidi/envtesting
-->
</html>
