<?php
/** @var \envtesting\Suit $suit */
/** @var \envtesting\Filter $filter */
?><!DOCTYPE html>
<html lang="en-us" dir="ltr">
<head>
	<meta charset="UTF-8">
	<title><?= $suit->getName() ?></title>
	<meta name="robots" content="noindex, nofollow, noarchive, noodp"/>

	<link rel="stylesheet" type="text/css" media="all"
	      href="//current.bootstrapcdn.com/bootstrap-v204/css/bootstrap-combined.min.css"/>
	<style type="text/css">
		tr.warning {
			background: #F89406;
		}

		tr.disabled, tr.disabled a {
			color: #a0a0a0;
		}

		tr.error, tr.exception {
			background: #BD362F;
		}

		tr.ok {
			background: #5BB75B;
		}

		.modal pre {
			overflow: auto;
			height: 150px;
		}

		body {
			padding-top: 20px;
		}

		.icon-info-sign {
			float: right;
		}

		table a {
			color: #333;
		}

		h3 {
			text-align: center;
			color: #05C;
			padding-bottom: 1em;
		}

		thead {
			border-top: 1px solid #ddd;
		}

		.btn-group {
			padding-bottom: 1em;
		}

		.footer {
			border-top: 1px solid #ddd;
			padding-top: 1em;
		}

		.footer .badge {
			margin: 0 2px;
		}
	</style>
</head>
<body>
<div class="container">
	<div class="row">
		<div class="span12">
			<h3><?= $suit->getName() ?></h3>

			<? if ($filter->isActive()) { ?>
			<div class="alert">
				<a href="?" class="close">&times;</a>Test results are filtered!
			</div>
			<? } ?>

			<table class="table table-condensed">
				<colgroup style="width:25px;"/>
				<colgroup style="width:80px;"/>
				<colgroup style="width:150px;"/>
				<colgroup style="width:150px;"/>
				<colgroup style="width:120px;"/>
				<colgroup style="width:100px;"/>
				<thead>
				<tr>
					<th></th>
					<th title="Warning | Error | Ok or disabled">Result</th>
					<th title="Unique test name">
						Name<?= $filter->name ? ' = <span class="label label-inverse">' . $filter->name . '</span>' : ''?>
					</th>
					<th title="Test group">
						Group<?= $filter->group ? ' = <span class="label label-inverse">' . $filter->group . '</span>' : ''?>
					</th>
					<th title="Test type">
						Type<?= $filter->type ? ' = <span class="label label-inverse">' . $filter->type . '</span>' : ''?>
					</th>
					<th title="Notice eg. stable server">Notice</th>
					<th title="Response message">Message</th>
				</tr>
				</thead>

				<tbody>

				<? foreach ($suit as $group => $tests) { ?>
					<? foreach ($tests as $order => $test/** @var \envtesting\Test $test */) { ?>
						<? $total++; ?>
					<tr class="<?= strtolower($test->getStatus())?>">
						<td>
							<i class="icon-<?= $test->isOk() ? 'ok' : 'remove' ?>"></i>
						</td>
						<td><?= $test->getStatus(); ?></td>
						<td><a href="?name=<?= $test->getName(); ?>"><?= $test->getName(); ?></a></td>
						<td><a href="?group=<?= $group ?>"><?= $group ?></a></td>
						<td>
							<a href="?type=<?= $test->getType(); ?>"><?= $test->getType(); ?></a>
						</td>
						<td><?= $test->getNotice(); ?></td>
						<td>
							<?= $test->getStatusMessage(); ?>
							<? if ($test->hasOptions()) { ?>
							<code>Options: <?= json_encode((array)$test->getOptions()); ?></code>
							<? } ?>
						</td>

					</tr>
						<? if ($test->isOk() && $test->isEnabled()) $ok++; ?>
						<? if (!$test->isEnabled()) $disabled++; ?>
						<? if ($test->isError()) $error++; ?>
						<? if ($test->isWarning()) $warning++; ?>
						<? } ?>

					<? } $enabled = $total - $disabled; ?>
				</tbody>
			</table>

			<div class="btn-group">
				<a href="" class="btn btn-primary"><i class="icon-refresh icon-white"></i> Refresh</a>
				<a href="csv<?= $_?>" class="btn"><i class="icon-arrow-down"></i> CSV</a>
				<? if ($filter->isActive()) { ?>
				<a href="?" class="btn btn-danger">Cancel filter</a>
				<? } ?>
			</div>

			<div class="footer">
				<? if ($disabled > 0) { ?>
				<span class="badge badge-info">
					<?= $disabled ?> DISABLED <?= $total ? round(100 * $disabled / $total) : 0 ?>%
				</span>
				<? } ?>
				<? if ($error > 0) { ?>
				<span class="badge badge-important">
					<?= $error ?> ERROR <?= $enabled ? round(100 * $error / $enabled) : 0 ?>%
				</span>
				<? } ?>
				<? if ($warning > 0) { ?>
				<span class="badge badge-warning">
					<?= $warning ?> WARNING <?= $enabled ? round(100 * $warning / $enabled) : 0 ?>%
				</span>
				<? } ?>
				<span class="badge badge-success">
					<?= $ok ?> OK <?=  ($total - $disabled) ? round(100 * $ok / ($total - $disabled)) : 0?>%
				</span>
				<span class="badge badge-inverse"><?= $total ?> TESTS</span>
				<a data-toggle="modal" href="#about" class="icon-info-sign"></a>
			</div>

		</div>
	</div>


	<div class="row">

		<div class="modal hide" id="about">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">×</button>
				<h3>Envtesting</h3>
			</div>
			<div class="modal-body">
				<p>Envtesting is fast simple and <strong>easy to use</strong> environment testing written in PHP.
					Can check library, services and services response. Produce console, HTML or CSV output.
				</p>

				<h4>Authors</h4>

				<p>
					<a href="http://www.wikidi.com">wikidi.com</a> +
					<a href="https://twitter.com/#!/OzzyCzech" title="Roman Ožana" target="_blank">@OzzyCzech</a>
				</p>

				<h4>Copyright & License</h4>

				<pre><? include __DIR__ . "/../../LICENSE.TXT"?></pre>

			</div>

			<div class="modal-footer">
				<a href="https://github.com/wikidi/envtesting" class="btn btn-primary" target="blank">Fork me on GitHub</a>
				<a href="#" class="btn btn-success" data-dismiss="modal">Thanks!</a>
			</div>
		</div>

	</div>
</div>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script src="//current.bootstrapcdn.com/bootstrap-v204/js/bootstrap.min.js"></script>
</body>
<!--
	Generated at <?= date('j.n.Y H:i:s') ?> by Envtesting
	https://github.com/wikidi/envtesting
-->
</html>